trigger:
- none

resources:
- repo: self

variables:
  tag: 'latest'
  ImageName: 'mabenwinston/volvo_test'

pool: volvo


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build the docker image
      inputs:
        repository: '$(ImageName)'
        command: 'build'
        dockerfile: '$(Build.SourcesDirectory)/python/Dockerfile'
        tags: $(tag)

    - task: Docker@2
      displayName: Push the docker image to Docker Hub
      inputs:
        containerRegistry: 'Docker Hub'
        repository: '$(ImageName)'
        imageName: 'python-image'
        command: 'push'
        tags: $(tag)

- stage: Deploy
  dependsOn: Build
  displayName: Deploy on EC2 kubernetes setup
  jobs:
    - job: Deploy
      displayName: Deploy
      steps:
      - script: |
          mkdir -p ~/ado_temp && cd ~/ado_temp
          git clone https://mabenwinston@dev.azure.com/mabenwinston/volvo_project/_git/volvo_project
          cd volvo_project/ansible
          ansible-playbook -i inventory/aws/hosts main.yml



  
