trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  ImageName: 'mabenwinston/volvo_test:$(Build.BuildId)'

pool: volvo


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build the docker image
      inputs:
        repository: 'mabenwinston/volvo_test'
        command: 'build'
        dockerfile: '$(Build.SourcesDirectory)/python/Dockerfile'

    - task: Docker@2
      displayName: Push the docker image to Docker Hub
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'mabenwinston/volvo_test'
        imageName: 'python-image'
        command: 'push'
